const ADD_PARAMETERS = "ADD_PARAMETERS";
const CHANGE_PARAMETERS = "CHANGE_PARAMETERS";
const LOGIN = "LOGIN";
const VERIFY_OTP = "VERIFY_OTP";
const RESEND_OTP = "RESEND_OTP";
const ADD_PATIENT = "ADD_PATIENT";
const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
const GET_PATIENTS = "GET_PATIENTS";
const SET_TOXIC = "SET_TOXIC";
const UNSET_TOXIC = "UNSET_TOXIC";
const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
const CHANGE_PRESCRIPTION = "CHANGE_PRESCRIPTION";
const SUBMIT_APPOINTMENT = "SUBMIT_APPOINTMENT";
const RE_SUBMIT_APPOINTMENT = "RE_SUBMIT_APPOINTMENT";
const GET_APPOINTMENTS = "GET_APPOINTMENTS";
const GET_PATIENT_APPOINTMENTS = "GET_PATIENT_APPOINTMENTS";
const SET_APPOINTMENT_IN = "SET_APPOINTMENT_IN";
const SET_APPOINTMENT_OUT = "SET_APPOINTMENT_OUT";
const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";
const RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT";
const GET_AUDIT_LOGS = "GET_AUDIT_LOGS";
const GET_LOGIN_AUDIT_LOGS = "GET_LOGIN_AUDIT_LOGS";
const DELETE_AUDIT_LOG = "DELETE_AUDIT_LOG";
const VERIFY_EMAIL = "VERIFY_EMAIL";
const ACCEPT_TERMS_AND_CONDITIONS = "ACCEPT_TERMS_AND_CONDITIONS";
const FORGOT_PASSWORD = "FORGOT_PASSWORD";
const RESET_PASSWORD = "RESET_PASSWORD";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";
const ADD_FEE = "ADD_FEE";
const UPDATE_FEE = "UPDATE_FEE";
const DELETE_FEE = "DELETE_FEE";
const ADD_PAYMENT_QR = "ADD_PAYMENT_QR";
const UPDATE_PAYMENT_QR = "UPDATE_PAYMENT_QR";
const ADD_SIGNATURE = "ADD_SIGNATURE";
const UPDATE_SIGNATURE = "UPDATE_SIGNATURE";
const ADD_LOGO = "ADD_LOGO";
const UPDATE_LOGO = "UPDATE_LOGO";
const ADD_CHECK_IN_OUT_TINE = "ADD_CHECK_IN_OUT_TINE";
const UPDATE_CHECK_IN_OUT_TINE = "UPDATE_CHECK_IN_OUT_TINE";
const UPDATE_DOCTOR = "UPDATE_DOCTOR";
const GET_DOCTOR = "GET_DOCTOR";
const SET_CLINIC_START_END_TIME = "SET_CLINIC_START_END_TIME";
const UPDATE_CLINIC_START_END_TIME = "UPDATE_CLINIC_START_END_TIME";
const CREATE_SHIFT_TIME = "CREATE_SHIFT_TIME";
const UPDATE_SHIFT_TIME = "UPDATE_SHIFT_TIME";
const ADD_RECEPTIONIST = "ADD_RECEPTIONIST";
const EDIT_RECEPTIONIST = "EDIT_RECEPTIONIST";
const REMOVE_RECEPTIONIST = "REMOVE_RECEPTIONIST";
const CHANGE_PROFILE = "CHANGE_PROFILE";
const RECEPTIONIST_CHECKIN = "RECEPTIONIST_CHECKIN";
const RECEPTIONIST_CHECKOUT = "RECEPTIONIST_CHECKOUT";
const GET_ALL_RECEPTIONISTS = "GET_ALL_RECEPTIONISTS";
const GET_RECEPTIONIST_BY_ID = "GET_RECEPTIONIST_BY_ID";
const GET_RECEPTIONIST_ATTENDANCE_STATS = "GET_RECEPTIONIST_ATTENDANCE_STATS";
const GET_RECEPTIONIST_ATTENDANCE_HISTORY =
  "GET_RECEPTIONIST_ATTENDANCE_HISTORY";
const ADD_MEDICINE = "ADD_MEDICINE";
const GET_ALL_MEDICINES = "GET_ALL_MEDICINES";
const EDIT_MEDICINE = "EDIT_MEDICINE";
const DELETE_MEDICINE = "DELETE_MEDICINE";
const BULK_UPLOAD_MEDICINES = "BULK_UPLOAD_MEDICINES";
const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

module.exports = {
  ADD_PARAMETERS,
  CHANGE_PARAMETERS,
  LOGIN,
  VERIFY_OTP,
  RESEND_OTP,
  ADD_PATIENT,
  BOOK_APPOINTMENT,
  GET_PATIENTS,
  SET_TOXIC,
  UNSET_TOXIC,
  ADD_PRESCRIPTION,
  CHANGE_PRESCRIPTION,
  SUBMIT_APPOINTMENT,
  RE_SUBMIT_APPOINTMENT,
  GET_APPOINTMENTS,
  GET_PATIENT_APPOINTMENTS,
  SET_APPOINTMENT_IN,
  SET_APPOINTMENT_OUT,
  CANCEL_APPOINTMENT,
  RESCHEDULE_APPOINTMENT,
  GET_AUDIT_LOGS,
  GET_LOGIN_AUDIT_LOGS,
  DELETE_AUDIT_LOG,
  VERIFY_EMAIL,
  ACCEPT_TERMS_AND_CONDITIONS,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  ADD_FEE,
  UPDATE_FEE,
  DELETE_FEE,
  CHANGE_PASSWORD,
  ADD_PAYMENT_QR,
  UPDATE_PAYMENT_QR,
  ADD_SIGNATURE,
  UPDATE_SIGNATURE,
  ADD_LOGO,
  UPDATE_LOGO,
  ADD_CHECK_IN_OUT_TINE,
  UPDATE_CHECK_IN_OUT_TINE,
  UPDATE_DOCTOR,
  GET_DOCTOR,
  SET_CLINIC_START_END_TIME,
  UPDATE_CLINIC_START_END_TIME,
  CREATE_SHIFT_TIME,
  UPDATE_SHIFT_TIME,
  ADD_RECEPTIONIST,
  EDIT_RECEPTIONIST,
  REMOVE_RECEPTIONIST,
  CHANGE_PROFILE,
  RECEPTIONIST_CHECKIN,
  RECEPTIONIST_CHECKOUT,
  GET_ALL_RECEPTIONISTS,
  GET_RECEPTIONIST_BY_ID,
  GET_RECEPTIONIST_ATTENDANCE_STATS,
  GET_RECEPTIONIST_ATTENDANCE_HISTORY,
  ADD_MEDICINE,
  GET_ALL_MEDICINES,
  EDIT_MEDICINE,
  DELETE_MEDICINE,
  BULK_UPLOAD_MEDICINES,
  GET_NOTIFICATIONS,
  MARK_NOTIFICATION_READ,
  DELETE_NOTIFICATION,
};
